<?php
declare(strict_types=1);

use Fintecture\Payment\Block\CustomLogo;

/** @var CustomLogo $block */
$showLogo = $block->getShowLogo();
if ($showLogo) {
?>
    <style>
        .checkout-index-index .payment-method .payment-method-title label.label.img_label:after {
            display: inline-block;
            vertical-align: middle;
            position: relative;
            top: -2px;
            height: 22.1px;
            width: 104px;
            margin-left: 10px;
            content: '';
            background: url('https://assets.fintecture.com/img/new-checkout/magento/fintecture.svg');
            background-repeat: no-repeat;
            background-size: contain;
        }
    </style>
<?php
}
?>
